name: Lint
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: Checker
    steps:
      - name: Actions - Checkout
        uses: actions/checkout@v4

      - name: Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: Installing Dependencies
        run: npm ci

      - name: Checking Lint Rules
        run: npm run lint
